name: Android CI

on:
  pull_request:
    paths:
      - 'android/**'
      - '.github/workflows/android.yml'
  push:
    branches:
      - main
    paths:
      - 'android/**'
      - '.github/workflows/android.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew
        working-directory: .
      
      - name: Build with Gradle
        run: ./gradlew build
        working-directory: android
      
      - name: Run tests
        run: ./gradlew test
        working-directory: android
      
      - name: Lint check
        run: ./gradlew lint
        working-directory: android
        continue-on-error: true
