name: Android CI

on:
  pull_request:
    paths:
      - 'android/**'
      - '.github/workflows/android.yml'
  push:
    branches:
      - main
    paths:
      - 'android/**'
      - '.github/workflows/android.yml'

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
      
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
      
      - name: Cache Gradle dependencies
        uses: actions/cache@v4
        with:
          path: |
            android/.gradle
            android/build
          key: ${{ runner.os }}-gradle-${{ hashFiles('android/**/*.gradle*', 'android/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      
      - name: Grant execute permission for gradlew
        run: chmod +x android/gradlew
        working-directory: .
      
      - name: Run tests
        run: ./gradlew test --no-daemon
        working-directory: android