name: Mirrors

on:
  push:
    branches: [ main ]
    paths:
      - "android/**"
      - "server/**"
      - ".github/workflows/mirrors.yml"

permissions:
  contents: write

jobs:
  mirror-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure Git
        run: |
          git config user.name "ikiugu"
          git config user.email "ikiugualf@gmail.com"

      - name: Use PAT for github.com
        run: git config url."https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Split android subtree
        id: split_android
        run: echo "sha=$(git subtree split --prefix=android HEAD)" >> $GITHUB_OUTPUT

      - name: Push to SkyTrackAndroid
        run: |
          if git ls-remote --heads https://github.com/ikiugu/SkyTrackAndroid.git main 2>/dev/null | grep -q main; then
            echo "Branch exists, using force push"
            git push --force https://github.com/ikiugu/SkyTrackAndroid.git ${{ steps.split_android.outputs.sha }}:main
          else
            echo "First push to empty repository"
            git push https://github.com/ikiugu/SkyTrackAndroid.git ${{ steps.split_android.outputs.sha }}:main
          fi

  mirror-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Configure Git
        run: |
          git config user.name "ikiugu"
          git config user.email "ikiugualf@gmail.com"

      - name: Use PAT for github.com
        run: git config url."https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - name: Split server subtree
        id: split_server
        run: echo "sha=$(git subtree split --prefix=server HEAD)" >> $GITHUB_OUTPUT

      - name: Push to SkyTrackServer
        run: |
          if git ls-remote --heads https://github.com/ikiugu/SkyTrackServer.git main 2>/dev/null | grep -q main; then
            echo "Branch exists, using force push"
            git push --force https://github.com/ikiugu/SkyTrackServer.git ${{ steps.split_server.outputs.sha }}:main
          else
            echo "First push to empty repository"
            git push https://github.com/ikiugu/SkyTrackServer.git ${{ steps.split_server.outputs.sha }}:main
          fi