name: Server CI

on:
  pull_request:
    paths:
      - 'server/**'
      - '.github/workflows/server.yml'
  push:
    branches:
      - main
    paths:
      - 'server/**'
      - '.github/workflows/server.yml'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: 'gradle'
      
      - name: Start Kafka with Docker Compose
        run: |
          docker-compose up -d
        working-directory: server
        continue-on-error: true
      
      - name: Grant execute permission for gradlew
        run: chmod +x server/gradlew
        working-directory: .
      
      - name: Build with Gradle
        run: ./gradlew build
        working-directory: server
      
      - name: Run tests
        run: ./gradlew test
        working-directory: server
      
      - name: Stop Kafka
        run: |
          docker-compose down
        working-directory: server
        if: always()
        continue-on-error: true
